webtalk_init -webtalk_dir /home/kammce/Documents/University/CMPE127/CMPE127-Toolkit/CMPE127-Toolkit.sim/sim_1/behav/xsim/xsim.dir/Test_VGA_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Feb 19 18:47:56 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e3d9ad2f-3919-4764-be05-5fc84d355e3a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b88e81cc53414897a6cdb318bade6df8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "270" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2800.593 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "133744_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3315420749 -regid "" -xml /home/kammce/Documents/University/CMPE127/CMPE127-Toolkit/CMPE127-Toolkit.sim/sim_1/behav/xsim/xsim.dir/Test_VGA_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/kammce/Documents/University/CMPE127/CMPE127-Toolkit/CMPE127-Toolkit.sim/sim_1/behav/xsim/xsim.dir/Test_VGA_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/kammce/Documents/University/CMPE127/CMPE127-Toolkit/CMPE127-Toolkit.sim/sim_1/behav/xsim/xsim.dir/Test_VGA_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
